AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates DynamoDB table to store form data

Parameters:
  ProjectName:
    Description: Project name used to identify created AWS resources
    Type: String
  TableName:
    Type: String
    Description: Form data table name

Resources:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  APIGWRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  APIGWPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows Api Gateway to access Form Data table
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt FormDataTable.Arn
      Roles:
        - !Ref APIGWRole
