AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates DynamoDB table to store form data

Parameters:
  ProjectName:
    Description: Project name used to identify created AWS resources
    Type: String
  TableName:
    Type: String
    Description: Form data table name

Resources:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName
