AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates DynamoDB table to store form data

Parameters:
  ProjectName:
    Description: Project name used to identify created AWS resources
    Type: String
  TableName:
    Type: String
    Description: Form data table name

Resources:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  APIGWRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  APIGWPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows Api Gateway to access Form Data table
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt FormDataTable.Arn
      Roles:
        - !Ref APIGWRole

  APIGW:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: !Sub ${ProjectName} APIs
      # DisableExecuteApiEndpoint: true # TODO: disable when custom domain name provided
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref ProjectName
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  FormDataInputModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Description: A form data input model
      Name: FormDataRequest
      RestApiId: !Ref APIGW
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        title: FormDataInputModel
        type: object
        properties:
          email:
            type: string
          fullName:
            type: string
          comment:
            type: string
            maxLength: 255
        required:
          - email
          - fullName

  FormDataOutputModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Description: A response on form data processing
      Name: FormDataResponse
      RestApiId: !Ref APIGW
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        title: FormDataOutputModel
        type: object
        properties:
          message:
            type: string
