AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates WAF WebACL for the project

Parameters:
  ProjectName:
    Description: Project name used to identify created AWS resources
    Type: String

Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Description: !Sub Web ACL for ${ProjectName} project distribution
      Name: !Sub ${ProjectName}-web-acl
      Scope: CLOUDFRONT
      VisibilityConfig:
        SampledRequestsEnabled: "true"
        CloudWatchMetricsEnabled: "true"
        MetricName: !Sub ${ProjectName}-metric
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

Outputs:
  WebACLId:
    Value: !GetAtt WebACL.Id